#!/bin/bash

source /common/conf/bashrc

module load python/3.latest

now=$1
while [ "$now" != $(date +%m/%d/%y -d $2) ] ;
do
    echo $now    
    ./PopulateDatabase $now
    now=$(date +%m/%d/%y -d "$now + 1 day")
done
